/**
 * Report builder — Caselog's killer feature. Produces a clean, chronological
 * HTML document from a case's incidents, expenses, and exchanges, which
 * expo-print renders to a shareable PDF for the user's attorney/mediator.
 *
 * IMPORTANT (positioning/liability): label the output as ORGANIZED PERSONAL
 * DOCUMENTATION to share with an attorney. Do NOT assert it is
 * "court-admissible" or constitutes legal advice. The disclaimer below is
 * intentional — keep it. See BUILD_TO_MVP.md → "Positioning & liability".
 */
import type {
  CaseProfile,
  ExchangeEvent,
  Expense,
  IncidentEntry,
} from "@/data/types";

const DISCLAIMER =
  "This document was generated by the user from self-entered records for the " +
  "purpose of organizing personal documentation to share with their attorney " +
  "or mediator. It is not legal advice and makes no representation as to " +
  "admissibility in any proceeding.";

function fmtDate(iso: string): string {
  return new Date(iso).toLocaleString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });
}

export function fmtMoney(cents: number): string {
  return `$${(cents / 100).toFixed(2)}`;
}

export interface ReportData {
  profile: CaseProfile;
  incidents: IncidentEntry[];
  expenses: Expense[];
  exchanges: ExchangeEvent[];
}

export function buildReportHtml(data: ReportData): string {
  const { profile, incidents, expenses, exchanges } = data;
  const balance = expenses.reduce((s, e) => s + e.owedToMeCents, 0);

  const incidentRows = incidents
    .map(
      (i) => `
      <tr>
        <td>${fmtDate(i.occurredAt)}</td>
        <td>${escapeHtml(i.category)}</td>
        <td><strong>${escapeHtml(i.title)}</strong><br/>${escapeHtml(i.details)}
          ${i.attachments.length ? `<br/><em>${i.attachments.length} attachment(s)</em>` : ""}
        </td>
        <td class="ts">logged ${fmtDate(i.createdAt)}</td>
      </tr>`
    )
    .join("");

  const expenseRows = expenses
    .map(
      (e) => `
      <tr>
        <td>${fmtDate(e.occurredAt)}</td>
        <td>${escapeHtml(e.description)}</td>
        <td>${fmtMoney(e.amountCents)}</td>
        <td>${escapeHtml(e.split)}</td>
        <td>${fmtMoney(e.owedToMeCents)}</td>
      </tr>`
    )
    .join("");

  const exchangeRows = exchanges
    .map(
      (x) => `
      <tr>
        <td>${fmtDate(x.scheduledAt)}</td>
        <td>${x.occurred ? (x.actualAt ? fmtDate(x.actualAt) : "occurred") : "DID NOT OCCUR"}</td>
        <td>${escapeHtml(x.note ?? "")}</td>
      </tr>`
    )
    .join("");

  return `<!doctype html><html><head><meta charset="utf-8"/>
  <style>
    body { font-family: -apple-system, Helvetica, Arial, sans-serif; color: #161B22; padding: 24px; }
    h1 { color: #1B2A4A; margin-bottom: 0; }
    h2 { color: #1B2A4A; border-bottom: 2px solid #E1E5EB; padding-bottom: 4px; margin-top: 28px; }
    .sub { color: #5C6675; margin-top: 4px; }
    table { width: 100%; border-collapse: collapse; font-size: 12px; margin-top: 8px; }
    th, td { text-align: left; vertical-align: top; padding: 6px 8px; border-bottom: 1px solid #E1E5EB; }
    th { background: #F4F6F9; }
    .ts { color: #5C6675; font-size: 10px; }
    .balance { font-size: 16px; font-weight: 700; color: #2F6F6B; }
    .disclaimer { margin-top: 32px; font-size: 10px; color: #5C6675; border-top: 1px solid #E1E5EB; padding-top: 8px; }
  </style></head><body>
    <h1>Documentation Report</h1>
    <div class="sub">${escapeHtml(profile.label)} ·
      ${profile.childrenFirstNames.map(escapeHtml).join(", ")}</div>
    <div class="sub">Generated ${fmtDate(new Date().toISOString())}</div>

    <h2>Incident Log (${incidents.length})</h2>
    <table><tr><th>When it happened</th><th>Category</th><th>Detail</th><th>Record</th></tr>
      ${incidentRows || `<tr><td colspan="4">No incidents logged.</td></tr>`}</table>

    <h2>Expenses</h2>
    <p class="balance">Balance owed to me: ${fmtMoney(balance)}</p>
    <table><tr><th>Date</th><th>Description</th><th>Amount</th><th>Split</th><th>Owed to me</th></tr>
      ${expenseRows || `<tr><td colspan="5">No expenses logged.</td></tr>`}</table>

    <h2>Custody Exchanges</h2>
    <table><tr><th>Scheduled</th><th>Actual</th><th>Note</th></tr>
      ${exchangeRows || `<tr><td colspan="3">No exchanges logged.</td></tr>`}</table>

    <div class="disclaimer">${DISCLAIMER}</div>
  </body></html>`;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
